### ISSUE TITLE
Request to be a contibutor

### ISSUE THREAD

**Issue by taki-on** [eliperkins/Catalogue#1]
Hey!

I found that this script is optimized for the old color catalogue folder structure, so it does not work anymore. I have a branch where I updated the logic adopting the new folder structure, but I can't open a PR, since I do not have permission.

Can you help me? :) @eliperkins

**Comment by eliperkins** [comment]
Invite sent!

**Comment by eliperkins** [comment]
Related: this tool is fairly specific to `github/mobile-ios` currently. I don't have much intention on treating it as a proper open-source project and generalizing it, so if we want to move this tool/package into that repo, I think that's okay too! It might make it easier to maintain.
